# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 56FL001's Radio Website
email:
description: 56FL001 Timo's Radio Website
baseurl: "http://56fl001.fldx.org/" # the subpath of your site, e.g. /blog
url: "http://56fl001.fldx.org" # the base hostname & protocol for your site
twitter_username: 56fl001
github_username:  teear

# Build settings
markdown: kramdown

#
gems:
  - jekyll-sitemap
